[package]
name = "aoc2021"
version = "0.1.0"
edition = "2021"

[lib]
name = "utils"
path = "src/lib.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.68"
itertools = "0.10.5"
